### ISSUE TITLE
Error compile 

### ISSUE THREAD

**Issue by Motorheadx** [Shoxxo/Sunwell#14]
/usr/bin/ld: ../../server/shared/libshared.a(Util.cpp.o): неопределённая ссылка на символ «pthread_getspecific@@GLIBC_2.0»
//lib/i386-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [src/tools/mmaps_generator/mmaps_generator] Ошибка 1
make[1]: *** [src/tools/mmaps_generator/CMakeFiles/mmaps_generator.dir/all] Ошибка 2
make[1]: *** Ожидание завершения заданий...

**Comment by igorkur** [comment]
map extractor compilation error

**Comment by Shoxxo** [comment]
https://travis-ci.org/Shoxxo/Sunwell/builds/115576178

Wait to finish.

**Comment by Motorheadx** [comment]
can you make it?

**Comment by Motorheadx** [comment]
my OS is Debian =))

**Comment by Shoxxo** [comment]
i use debian and linux, i use at my privat server too debian jessy :) for me it works fine :) you can send me your contact information and i will add you :)

**Comment by igorkur** [comment]
And what is the address of the server ?

**Comment by Shoxxo** [comment]
you can just follow my live development stream : http://twitch.rv/LoomarTV and we will see if your issue and my version are same :)

**Comment by Motorheadx** [comment]
what should I do about this error? will help to fix it? =))

**Comment by Motorheadx** [comment]
good work npc command=)

**Comment by Shoxxo** [comment]
Pull latest core rev :) git pull and it will resolve that issue ;) Travis says oka :+1:

**Comment by igorkur** [comment]
окей =)

**Comment by Shoxxo** [comment]
Russian :) <img src="http://icons.iconarchive.com/icons/gosquared/flag/64/Russia-icon.png" />
