### ISSUE TITLE
Fix you help

### ISSUE THREAD

**Issue by igorkur** [Shoxxo/Sunwell#18]
Some fixes to help you https://github.com/callmephil/SunWellCore/commits/master

**Comment by Motorheadx** [comment]
With all my heart! xD

**Comment by Shoxxo** [comment]
Don't need id, i asked Trinitycore devs and the answere was simple : We do not help projects with a core full of hacks.

**Comment by igorkur** [comment]
This is not my project , it is a reference to the fix, I found on the internet

**Comment by Shoxxo** [comment]
need fix more -pthread, i found references but not now who is to set this...
http://askubuntu.com/questions/308863/compiling-apib-undefined-reference-to-symbol-pthread-createglibc-2-2-5
