### ISSUE TITLE
DBC

### ISSUE THREAD

**Issue by igorkur** [Shoxxo/Sunwell#2]
Change DBC.Locale = 255 to 2 nothing happend.

Server log:
Using enUS DBC Locale as default. All available DBC locales: ruRU enUS

Core problem or what?

**Comment by Shoxxo** [comment]
Only use 255. This is default to work correct.

**Comment by Motorheadx** [comment]
locales table do not translate the text

**Comment by Shoxxo** [comment]
Do not open a new Issue, i will make a lookin into the problem. But we need own dbc files that are a bit modified that player have no issues.
