### ISSUE TITLE
/who

### ISSUE THREAD

**Issue by igorkur** [Shoxxo/Sunwell#5]
AllowTwoSide.WhoList = 1

not work

**Comment by Shoxxo** [comment]
3c754d371e57cbeffdaec29f6c9348141c3e87d9

Test it, i will wait on travis...

**Comment by Shoxxo** [comment]
Fixxed in : 205c6e6fdbd113fdb8ae7c18089c4929917eae0e

Horde and Alliance both visible in /who

<img src="http://i.imgur.com/mgGkage.jpg" />
